"""
HAL Interface — The abstract contract that ANY GPU backend must satisfy.
8 methods = full GPU compute capability on any hardware in the world.

To add a new backend (Vulkan, Metal, Level Zero, SYCL):
    1. Subclass HALBackend
    2. Implement the 8 abstract methods
    3. Register in torchcl/hal/__init__.py
    That's it. All 6 OjasX libraries work instantly on the new hardware.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Any, Sequence

import numpy as np


# ── Data Types ───────────────────────────────────────────────────────

class PrecisionPolicy(Enum):
    """User-controllable precision policy."""
    SAFE = auto()    # fp32 always for training; auto fp16 for inference when safe
    AUTO = auto()    # Full AMP: fp16 forward, fp32 gradients
    EXACT = auto()   # fp32 everywhere, bit-perfect reproducibility


@dataclass
class DeviceInfo:
    """Hardware capabilities of the detected GPU."""
    name: str
    vendor: str                      # "Intel", "AMD", "Apple", "Qualcomm", "ARM", "NVIDIA"
    compute_units: int
    global_mem_mb: int
    local_mem_kb: int
    max_workgroup: int
    supports_fp16: bool = False
    supports_bf16: bool = False
    supports_int8: bool = False
    supports_subgroups: bool = False
    preferred_vector_width: int = 4
    max_bandwidth_gbps: float = 0.0
    driver_version: str = ""

    @property
    def vendor_short(self) -> str:
        """Normalized vendor tag for kernel synthesis."""
        v = self.vendor.lower()
        if "intel" in v: return "intel"
        if "amd" in v or "radeon" in v or "advanced" in v: return "amd"
        if "apple" in v: return "apple"
        if "qualcomm" in v or "adreno" in v: return "qualcomm"
        if "arm" in v or "mali" in v: return "arm"
        if "nvidia" in v: return "nvidia"
        return "generic"


@dataclass
class BufferHandle:
    """Opaque handle to a GPU memory buffer."""
    raw: Any                         # Backend-specific object (cl.Buffer, vk.Buffer, etc.)
    nbytes: int
    capacity: int                    # Actual allocated size (may be rounded up)
    dtype: np.dtype | None = None
    shape: tuple | None = None
    _id: int = 0                     # Unique ID for tracking

    def __repr__(self) -> str:
        return f"BufferHandle(id={self._id}, {self.nbytes}B, shape={self.shape}, dtype={self.dtype})"


@dataclass
class KernelHandle:
    """Opaque handle to a compiled GPU kernel."""
    raw: Any                         # Backend-specific compiled kernel
    name: str
    source_file: str = ""
    is_synthesized: bool = False     # True if generated by KernelSynthesizer


# ── Abstract Backend ─────────────────────────────────────────────────

class HALBackend(ABC):
    """
    The Universal GPU Backend Interface.
    
    Any GPU in the world can run OjasX by implementing these 8 methods.
    This is the single point where hardware-specific code lives.
    Everything above this layer is pure, portable Python.
    """

    device_info: DeviceInfo

    # ── 1. Initialization ────────────────────────────────────────

    @abstractmethod
    def init(self, device_index: int = 0) -> DeviceInfo:
        """Discover and initialize the GPU device.
        Returns device capabilities. Called once at startup.
        """
        ...

    # ── 2. Memory Management ─────────────────────────────────────

    @abstractmethod
    def allocate(self, nbytes: int, dtype: np.dtype | None = None,
                 shape: tuple | None = None) -> BufferHandle:
        """Allocate GPU memory. Returns an opaque buffer handle."""
        ...

    @abstractmethod
    def free(self, handle: BufferHandle) -> None:
        """Release GPU memory back to the pool."""
        ...

    @abstractmethod
    def host_to_device(self, host_array: np.ndarray,
                       handle: BufferHandle) -> None:
        """Copy data from CPU numpy array to GPU buffer."""
        ...

    @abstractmethod
    def device_to_host(self, handle: BufferHandle,
                       shape: tuple, dtype: np.dtype) -> np.ndarray:
        """Copy data from GPU buffer back to CPU numpy array."""
        ...

    # ── 3. Kernel Execution ──────────────────────────────────────

    @abstractmethod
    def compile_kernel(self, source: str,
                       kernel_name: str) -> KernelHandle:
        """Compile GPU kernel source code. Returns a kernel handle.
        Implementations should cache compiled binaries.
        """
        ...

    @abstractmethod
    def enqueue_kernel(self, kernel: KernelHandle,
                       global_size: tuple, local_size: tuple | None,
                       *args: Any) -> None:
        """Enqueue a compiled kernel for execution on the GPU."""
        ...

    # ── 4. Synchronization ───────────────────────────────────────

    @abstractmethod
    def synchronize(self) -> None:
        """Block until all enqueued GPU operations complete."""
        ...

    # ── Non-abstract utilities ───────────────────────────────────

    def compute_global_size(self, n: int, local_size: int = 256) -> int:
        """Round up n to nearest multiple of local_size."""
        return ((n + local_size - 1) // local_size) * local_size
