#ifndef OJASX_BACKENDS_COMPUTE_CATEGORY_HPP
#define OJASX_BACKENDS_COMPUTE_CATEGORY_HPP

#include <iostream>
#include <string>
#include "../core/category.hpp"

namespace ojasx::backends {

/// Fused Compute Block Object
struct FusedKernelBlock {
    std::string kernel_name;
    std::string fused_code;
    std::size_t launch_workgroups;

    void print_kernel_info() const {
        std::cout << "  [Compute Category] Fused Kernel Block: " << kernel_name
                  << " (Workgroups: " << launch_workgroups << ")\n";
    }
};

/// Functor F_comp: Maps Composition Pipelines into Fused Compute Blocks
struct ComputeFusionFunctor {
    template <typename CompositionPipeline>
    FusedKernelBlock fuse_pipeline(const CompositionPipeline&, std::string_view name) const {
        return FusedKernelBlock{
            .kernel_name = std::string(name),
            .fused_code = "// Monoidally Fused Kernel Logic Generated by OjasX-ACT\n",
            .launch_workgroups = 256
        };
    }
};

} // namespace ojasx::backends

#endif // OJASX_BACKENDS_COMPUTE_CATEGORY_HPP
